### ISSUE TITLE
Laziness vs Strict issues?

### ISSUE THREAD

**Issue by JordanMartinez** [Woody88/purescript-wai#2]
Since Haskell is lazy by default, they can have a lot of fields in their Record type for `Request`. If we port their model 1-to-1, will there be performance issues for doing that?

**Comment by Woody88** [comment]
Hmm... I don't think that it's a big issue aside from probably always evaluating a large body when not needed. The rest of the fields are just information that you would find when parsing headers which should be pretty cheap. Am I missing something?

**Comment by JordanMartinez** [comment]
No, that was just a general question I thought would be worth raising. I'll close this.
