### ISSUE TITLE
Add `http-types` to ReadMe's additions to official package set

### ISSUE THREAD

**Issue by JordanMartinez** [Woody88/purescript-wai#3]
I wanted to try using this in a side project, but I'm not sure how to compile it because `http-types` isn't in the package set and your `spago.dhall` is referencing a local project on your computer.

So....

**Comment by Woody88** [comment]
Hi @JordanMartinez, yea thanks for catching that. I was doing a lot of changes on my http-types lib, and it was much easier to refer to my local path than to my remote repo. It is not fixed, try again and let me know.

**Comment by JordanMartinez** [comment]
Thanks! I can add it to my package set now.

**Comment by JordanMartinez** [comment]
Not sure when you plan on doing this, but you should update the `additions` part of the package set on the ReadMe to include `http-types`
