### ISSUE TITLE
Consider merges with other, preexisting wai libs

### ISSUE THREAD

**Issue by paluh** [Woody88/purescript-wai#6]
I think that these libs can be seen as really valuable source of types and solutions - especially @julienchan lib:

https://github.com/julienchan/purescript-node-wai

https://github.com/matthieubulte/purescript-wai

If you consider moving this lib to the _purescript-node-contrib_ and we want to establish some sort of a standard here then probably we should consider merging some parts from there and also push into tighter collaboration as we are still a really tiny community and there is no space for such a separation I think ;-)
What do you think?

**Comment by robertdp** [comment]
Those other libs haven't been updated in 4 and 6 years respectively. I don't even recognise the authors from the community...

**Comment by paluh** [comment]
@robertdp I've asked this question a few months ago. Please take into account how many type definition the first lib already provides:

https://github.com/julienchan/purescript-node-wai/tree/master/src/Network/HTTP

I thought that this could be an inspiration or direct source of some pieces. Another consideration was that even a link from these abandoned libs README to here could be a good way of organizing the ecosystem a bit.

Should I close this?

**Comment by robertdp** [comment]
@paluh Ah, so this was posted before Woody's continued work on [warp](https://github.com/Woody88/purescript-warp). Sorry, I read it without the context of time...

I think that unless there is a specific suggestion or improvement to make with this WAI, then this issue should be closed. And if there is a suggestion it should be a new issue.

Is there any value in asking the other libraries authors to update the READMEs? I usually search Pursuit when I'm looking for a library, and neither of those are on Pursuit.

**Comment by paluh** [comment]
Maybe, you are right :-) I'm just closing this for now.
